package www.top.com;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

public class details_activity extends AppCompatActivity {



    String details []={"1. Massachusetts Institute of Technology (MIT)"+"\n"+"2. Stanford University"+ "\n"+"3. Harvard University"+"\n"+"4. University of Oxford"+"\n"+"5. California Institute of Technology (Caltech)"+"\n"+"6. ETH Zurich (Swiss Federal Institute of Technology)"+"\n"+"7. University of Cambridge"+"\n"+"8. UCL (University College London)"+"\n"+"9. Imperial College London"+"\n"+"10. University of Chicago",
           "1. Bruges - Belgium"+"\n"+"2. Budapest - Hungary"+ "\n"+"3. Rome - Italy"+"\n"+"4. Florence - Italy"+"\n"+"5. Amsterdam - Netherlands"+"\n"+"6. Rio de Janeiro - Brazil"+"\n"+"7. Lisbon - Portugal"+"\n"+"8. Prague - Czechoslovakia"+"\n"+"9. Paris - France"+"\n"+"10. Venice - Italy",
            "1. Jeff Bezos — $113 B"+"\n"+"2. Bill Gates — $98 B"+ "\n"+"3. Bernard Arnault — $76 B"+"\n"+"4. Warren Buffett — $67.5 B"+"\n"+"5. Larry Ellison — $59 B"+"\n"+"6. Amancio Ortega — $55.1 B"+"\n"+"7.Mark Zuckerberg — $54.7 B"+"\n"+"8. Jim Walton — $54.6 B"+"\n"+"9. Alice Walton — $54.4 B"+"\n"+"10. Rob Walton — $54.1 B",
            "1. Lionel Messi — FC Barcelona"+"\n"+"2. Neymar — Paris Saint Germain"+ "\n"+"3. N'Golo Kante — Chelsea FC"+"\n"+"4. Virgil Van Dijk — Liverpool FC"+"\n"+"5. Kevin De Bruyne — Manchester City"+"\n"+"6. Kylian Mbappe — Paris Saint Germain"+"\n"+"7. Paul Pogba — Manchester United"+"\n"+"8. Eden Hazard — Real Madrid"+"\n"+"9. Sadio Mane — Liverpool FC"+"\n"+"10. Kalidou Koulibaly — SSC Napoli",
            "1. The Godfather (1972)"+"\n"+"2. The Shawshank Redemption (1994)"+ "\n"+"3. Schindler's List (1993)"+"\n"+"4. Raging Bull (1980)"+"\n"+"5. Casablanca (1942)"+"\n"+"6. Citizen Kane (1941)"+"\n"+"7. Gone with the Wind (1939)"+"\n"+"8. The Wizard of Oz (1939)"+"\n"+"9. One Flew Over the Cuckoo's Nest (1975)"+"\n"+"10. Lawrence of Arabia (1962)",
            "1. Toy Story 4 (2019)"+"\n"+"2. Spider-Man: Into the Spider-Verse (2018)"+ "\n"+"3. Inside Out (2015)"+"\n"+"4. Coco (2017)"+"\n"+"5. Snow White and the Seven Dwarfs (1937)"+"\n"+"6. Incredibles 2 (2018)"+"\n"+"7. Paddington 2 (2018)"+"\n"+"8. Zootopia (2016)"+"\n"+"9. Up (2009)"+"\n"+"10. Toy Story 2 (1999)",
            "1. Pride and Prejudice by Jane Austen"+"\n"+"2. 1984 by George Orwell"+ "\n"+"3. Crime and Punishment by Fyodor Dostoyevsky"+"\n"+"4. Hamlet by William Shakespeare"+"\n"+"5. One Hundred Years of Solitude by Gabriel García Márquez"+"\n"+"6. Anna Karenina by Leo Tolstoy"+"\n"+"7. The Stranger by Albert Camus"+"\n"+"8. The Odyssey by Homer"+"\n"+"9. Faust, First Part by Johann Wolfgang von Goethe"+"\n"+"10. The Man Without Qualities by Robert Musil",
            "1. Charles Chaplin"+"\n"+"2. Marlon Brando"+ "\n"+"3. Jack Nicholson"+"\n"+"4. Daniel Day-Lewis"+"\n"+"5. Tom Hanks"+"\n"+"6. Mohanlal"+"\n"+"7. Robert De Niro"+"\n"+"8. Anthony Hopkins"+"\n"+"9. Al Pacino"+"\n"+"10. Leonardo DiCaprio",
            "1. Scarlett Johansson"+"\n"+"2. Emma Watson"+ "\n"+"3. Margot Robbie"+"\n"+"4. Jennifer Lawrence"+"\n"+"5. Jennifer Aniston"+"\n"+"6. Anne Hathaway "+"\n"+"7. Gal Gadot"+"\n"+"8. Emma Stone"+"\n"+"9. Natalie Portman"+"\n"+"10. Angelina Jolie",
            "1. Massaman curry, Thailand"+"\n"+"2. Neapolitan pizza, Italy"+ "\n"+"3. Chocolate, Mexico"+"\n"+"4. Sushi, Japan"+"\n"+"5. Peking duck, China"+"\n"+"6. Hamburger, Germany"+"\n"+"7. Penang assam laksa, Malaysia"+"\n"+"8. Tom yum goong, Thailand"+"\n"+"9. Chicken muamba, Gabon"+"\n"+"10. Rendang, Indonesia",
            "1. Isaac Newton"+"\n"+"2. Aryabhatta"+ "\n"+"3. Galileo Galilei"+"\n"+"4. Thomas Alva Edison"+"\n"+"5. Leonardo da Vinci"+"\n"+"6. Stephen Hawking"+"\n"+"7. Terence Tao"+"\n"+"8.  Christopher Langan"+"\n"+"9. Kim Ung-Yong"+"\n"+"10. Judit Polgar",
            "1. Finland"+"\n"+"2. Norway"+ "\n"+"3. Switzerland"+"\n"+"4. Canada"+"\n"+"5. Sweden"+"\n"+"6. Denmark"+"\n"+"7. Germany"+"\n"+"8. United Kingdom"+"\n"+"9. Australia"+"\n"+"10. Netherlands",
            "1. Kevin Mitnick"+"\n"+"2. Jonathan James"+ "\n"+"3. Albert Gonzalez"+"\n"+"4. Kevin Poulsen"+"\n"+"5. Nasa Hacker Gary McKinnon"+"\n"+"6. Robert Tappan Morris"+"\n"+"7. Loyd Blankenship"+"\n"+"8. ulian Assange"+"\n"+"9. Guccifer 2.0"+"\n"+"10. Anonymous may be the most well-known “hacker” of all time, yet also the most nebulous. Anonymous is not a single person but rather a decentralized group of hackers with no true membership or hierarchy.",
            "1. Apple, Computer Hardware"+"\n"+"2. Microsoft, Software & Programming"+ "\n"+"3. Samsung Electronics, Semiconductors"+"\n"+"4. Alphabet, Computer Services"+"\n"+"5. AT&T, Telecommunications services"+"\n"+"6. Amazon, Internet & Catalog Retail"+"\n"+"7. Verizon Communications, Telecommunications services"+"\n"+"8. China Mobile, Telecommunications services"+"\n"+"9. Walt Disney, Broadcasting & Cable"+"\n"+"10. Facebook, Computer Services",
            "1. David Gandy"+"\n"+"2. Oliver Cheshire"+ "\n"+"3. Johannes Huebl"+"\n"+"4. Lucky Blue Smith"+"\n"+"5. Sean O’Pry"+"\n"+"6. Billy Huxley"+"\n"+"7. Jon Kortajarena"+"\n"+"8. Marlon Teixeira"+"\n"+"9. Isaac Carew"+"\n"+"10. Luka Sabbat",
            "1. Kendall Jenner"+"\n"+"2. Gisele Bündchen"+ "\n"+"3. Chrissy Teigen"+"\n"+"4. Adriana Lima"+"\n"+"5. Gigi Hadid"+"\n"+"6. Rosie Huntington-Whiteley"+"\n"+"7. Karlie Kloss"+"\n"+"8. Liu Wen"+"\n"+"9. Bella Hadid"+"\n"+"10. Ashley Graham",
            "1. Luis Fonsi – Despacito ft. Daddy Yankee"+"\n"+"2. Ed Sheeran – Shape of You"+ "\n"+"3. Wiz Khalifa – See You Again ft. Charlie Puth"+"\n"+"4. Mark Ronson – Uptown Funk ft. Bruno Mars"+"\n"+"5. PSY – Gangnam Style"+"\n"+"6. Justin Bieber – Sorry"+"\n"+"7. Maroon 5 – Sugar"+"\n"+"8. Katy Perry – Roar "+"\n"+"9. Ed Sheeran – Thinking Out Loud"+"\n"+"10. OneRepublic – Counting Stars",
            "1. Saul 'Canelo' Alvarez — 53 wins (36 knockouts)"+"\n"+"2. Vasyl Lomachenko — 14 wins (10 knockouts)"+ "\n"+"3.  Naoya Inoue — 19 wins (16 knockouts), unbeaten"+"\n"+"4. Tyson Fury — 30 wins (21 knockouts)"+"\n"+"5. Oleksandr Usyk — 17 wins (13 knockouts), unbeaten"+"\n"+"6. Terence Crawford — 35 wins (26 knockouts), unbeaten"+"\n"+"7. Errol Spence Jr. — 26 wins (21 knockouts), unbeaten"+"\n"+"8. Manny Pacquiao — 62 wins (39 knockouts) "+"\n"+"9. Juan Francisco Estrada — 40 wins (27 knockouts)"+"\n"+"10. Josh Taylor — 16 wins (12 knockouts), unbeaten",
            "1. Angela Merkel, Chancellor of Germany"+"\n"+"2. Christine Lagarde, Managing Director of the International Monetary Fund"+ "\n"+"3. Nancy Pelosi, 52nd Speaker of the U.S. House of Representatives"+"\n"+"4. Ursula von der Leyen, President of the European Commission"+"\n"+"5. Mary T. Barra, CEO of General Motors"+"\n"+"6. Melinda Gates, Co-founder of the Bill & Melinda Gates Foundation"+"\n"+"7. Abigail Johnson, President-CEO of Fidelity Investments"+"\n"+"8. Ana Patricia Botín, Executive Chairman of Banco Santander"+"\n"+"9. Ginni Rometty, CEO of IBM"+"\n"+"10. Marillyn Hewson, CEO of Lockheed Martin",
            "1. WhatsApp"+"\n"+"2. Facebook"+ "\n"+"3. Facebook Messenger"+"\n"+"4. Instagram"+"\n"+"5. Snapchat"+"\n"+"6. UC Browser"+"\n"+"7.Uber"+"\n"+"8. YouTube"+"\n"+"9. SHAREit"+"\n"+"10. Bitmoji",
            "1. Rodrigo Duterte - Filipinos"+"\n"+"2. Joko Widodo - Indonesia"+ "\n"+"3. Barack Obama - the 44th president of the United States of America"+"\n"+"4. Pervez Musharraf - Pakistani"+"\n"+"5. Xi Jinping - Donald Trump"+"\n"+"6. President of France - Emmanuel Macron"+"\n"+"7. Prime Minister of Japan - Shinzo Abe"+"\n"+"8. President of North Korea - Kim Jong-un - “Very Debatable on this one”."+"\n"+"9. President of India - Ram Nath Kovind"+"\n"+"10. President of Switzerland (Head of Government) - Ueli Bricklayer",
            "1. Machu Picchu, Peru"+"\n"+"2. The Grand Canyon, Arizona"+ "\n"+"3. Rome, Italy"+"\n"+"4. Maui, Hawaii"+"\n"+"5. Masai Mara, Kenya"+"\n"+"6. Montreal, Canada"+"\n"+"7. New Zealand"+"\n"+"8. Istanbul, Turkey"+"\n"+"9. Angkor Wat, Cambodia"+"\n"+"10. Paris, France",
            "1. Blue"+"\n"+"2. Red"+ "\n"+"3. Green"+"\n"+"4. Purple"+"\n"+"5. Black"+"\n"+"6. Orange"+"\n"+"7. Yellow"+"\n"+"8. Gold"+"\n"+"9. White"+"\n"+"10. Silver",
            "1. Kylie "+"\n"+"2. Cristiano Ronaldo "+ "\n"+"3. Selena Gomez"+"\n"+"4. Leo Messi"+"\n"+"5. Ariana Grande"+"\n"+"6. Kim Kardashian West"+"\n"+"7. Kendall"+"\n"+"8. Beyoncé"+"\n"+"9. neymarjr"+"\n"+"10. BILLIE EILISH",
            "1. Gabi Gregg "+"\n"+"2. Lisa Gachet"+ "\n"+"3. Wendy Nguyen"+"\n"+"4. Kat Farmer"+"\n"+"5. Lyn Slater"+"\n"+"6. Akanksha Redhu"+"\n"+"7. Tami Reed"+"\n"+"8. Kavita Donkersley "+"\n"+"9. Tanesha Awasthi"+"\n"+"10. Claire Goldsworthy",
            "1. Python"+"\n"+"2. JavaScript"+ "\n"+"3. Java"+"\n"+"4. Swift"+"\n"+"5. GoLang"+"\n"+"6. C#"+"\n"+"7. C++"+"\n"+"8. Scala"+"\n"+"9. Kotlin"+"\n"+"10. Ruby",
            "1. APPLE IPHONE 11"+"\n"+"2. ONEPLUS 8 PRO"+ "\n"+"3. APPLE IPHONE SE (2020)"+"\n"+"4. SAMSUNG GALAXY S20 ULTRA"+"\n"+"5. SAMSUNG GALAXY NOTE 10"+"\n"+"6.IPHONE 11 PRO"+"\n"+"7. GOOGLE PIXEL 4"+"\n"+"8. SAMSUNG GALAXY S10 PLUS"+"\n"+"9. SONY XPERIA 1"+"\n"+"10. GOOGLE PIXEL 3A",
            "1. ALBERT EINSTEIN"+"\n"+"2. MARIE CURIE"+ "\n"+"3. ALEXANDER GRAHAM BELL"+"\n"+"4. NEIL ARMSTRONG"+"\n"+"5. TONI MORRISON"+"\n"+"6. AMARTYA SEN"+"\n"+"7. JUDITH BUTLER"+"\n"+"8. BARRACK OBAMA"+"\n"+"9. GAYATRI CHAKRAVORTY SPIVAK"+"\n"+"10. JACK MA",
            "1. VARANASI, INDIA"+"\n"+"2. DELHI, INDIA"+ "\n"+"3. BAMENDA, CAMEROON"+"\n"+"4. PESHAWAR, PAKISTAN"+"\n"+"5. KAMPALA, UGANDA"+"\n"+"6. DOHA, QATAR"+"\n"+"7. JINING, CHINA"+"\n"+"8. DEZHOU, CHINA"+"\n"+"9. DZERSHINSK, RUSSIA"+"\n"+"10. NAGPUR, INDIA",
            "1. Ischemic heart disease, or coronary artery disease"+"\n"+"2. Stroke"+ "\n"+"3. Lower respiratory infections"+"\n"+"4. Chronic obstructive pulmonary disease"+"\n"+"5. Trachea, bronchus, and lung cancers"+"\n"+"6. Diabetes mellitus"+"\n"+"7. Alzheimer’s disease and other dementias"+"\n"+"8. Dehydration due to diarrheal diseases"+"\n"+"9. Tuberculosis"+"\n"+"10. Cirrhosis",
            "1. ABC"+"\n"+"2. Discovery Channel"+ "\n"+"3. CBS"+"\n"+"4. NBC"+"\n"+"5. History Channel"+"\n"+"6. National Geographic Channel"+"\n"+"7. FOX"+"\n"+"8. PBS"+"\n"+"9. HBO"+"\n"+"10. Comedy Central",
            "1. PUBG Mobile"+"\n"+"2. Call of Duty"+ "\n"+"3. Minecraft"+"\n"+"4. Clash Of Clans"+"\n"+"5. Free Fire"+"\n"+"6. Clash Royale"+"\n"+"7. Fortnite"+"\n"+"8. Assassin's Creed Identity"+"\n"+"9. Might and Magic: Era of Chaos"+"\n"+"10. War of the Visions: Final Fantasy Brave Exvius",
            "1. Burj Khalifa\tDubai (AE)"+"\n"+"2. Shanghai Tower\tShanghai (CN)"+ "\n"+"3. Makkah Royal Clock Tower\tMecca (SA)"+"\n"+"4. Ping An Finance Center\tShenzhen (CN)"+"\n"+"5. Lotte World Tower\tSeoul (KR)"+"\n"+"6. One World Trade Center\tNew York City (US)"+"\n"+"7. Guangzhou CTF Finance Centre\tGuangzhou (CN)"+"\n"+"8. Tianjin CTF Finance Centre\tTianjin (CN)"+"\n"+"9. CITIC Tower\tBeijing (CN)"+"\n"+"10. TAIPEI 101\tTaipei (CN)",
            "1. France - 89 million visitors"+"\n"+"2. Spain - 83 million visitors"+ "\n"+"3. United States - 80 million visitors"+"\n"+"4. China - 63 million visitors"+"\n"+"5. Italy - 62 million visitors"+"\n"+"6. Turkey - 46 million visitors"+"\n"+"7. Mexico - 41 million visitors"+"\n"+"8. Germany - 39 million visitors"+"\n"+"9. Thailand - 38 million visitors"+"\n"+"10. United Kingdom - 36 million visitors",
            "1. Olay"+"\n"+"2. Avon"+ "\n"+"3. L'Oreal"+"\n"+"4. Neutrogena"+"\n"+"5. Nivea"+"\n"+"6. Lancome"+"\n"+"7. Dove"+"\n"+"8. Estee Lauder"+"\n"+"9. Biore"+"\n"+"10. Shiseido",
            "1. Bugatti La Voiture Noire - $19 MILLION"+"\n"+"2. SWEPTAIL BY ROLLS ROYCE – $13 MILLION"+ "\n"+"3. KOENIGSEGG CCXR TREVITA – $4.8 MILLION"+"\n"+"4. LAMBORGHINI VENENO ROADSTER – $4.5 MILLION"+"\n"+"5. MCLAREN P1 LM – $3.6 MILLION"+"\n"+"6. LYKAN HYPERSPORT – $3.4 MILLION "+"\n"+"7. Bugatti Veyron Mansory Vivere - $3.4 MILLION "+"\n"+"8. ASTON MARTIN VALKYRIE – $3.2 MILLION "+"\n"+"9. FERRARI PININFARINA SERGIO – $3 MILLION "+"\n"+"10. PAGANI HUAYRA BC – $2.8 MILLION",
            "1. Dodge Tomahawk, 420 miles per hour"+"\n"+"2. Kawasaki Ninja H2R, Over 249 miles per hour"+ "\n"+"3. MTT Turbine Superbike Y2K, 227 miles per hour"+"\n"+"4. Kawasaki Ninja ZX-14R, 208.1 miles per hour"+"\n"+"5. Suzuki Hayabusa ,194 miles per hour"+"\n"+"6. Honda CBR1100XX Super Blackbird, 190 miles per hour"+"\n"+"7. Yamaha YZF  R1, 186 miles per hour"+"\n"+"8. MV Agusta F4 1000R, 184 miles per hour"+"\n"+"9. Aprilia RSV 1000R Mille, 175 miles per hour"+"\n"+"10. BMW K 1200S, 174 miles per hour",
            " Painters Who Are Shaping the New Decade"+"\n"+"1. Mandy El-Sayegh"+"\n"+"2. Tunji Adeniyi-Jones"+ "\n"+"3. Max Frintrop"+"\n"+"4. Viola Bittl"+"\n"+"5. Samuel Jablon"+"\n"+"6. Richie Culver"+"\n"+"7. Franziska Reinbothe"+"\n"+"8. Tomm El-Saieh"+"\n"+"9. Paul Weiner"+"\n"+"10. Clare Grill",
            "1. When Will You Marry, Paul Gauguin"+"\n"+"2. The Card Players, Paul Cezanne"+ "\n"+"3. Violet, Green and Red, Mark Rothko"+"\n"+"4. Les Femmes d’Alger (Version O), Picasso"+"\n"+"5. Woman III, Willem De Kooning"+"\n"+"6. 1948, Jackson Pollock"+"\n"+"7. Le Reve, Pablo Picasso"+"\n"+"8. Portrait of Adele Bloch Bauer, Gustav Klimt"+"\n"+"9. Portrait of Dr. Gachet, Van Gogh"+"\n"+"10. Three studies of Lucian Freud, Francis Bacon",
            "1. Automobile- Approximate Date: 1884 A.D."+"\n"+"2. Recording - Approximate Date: 1860 A.D."+ "\n"+"3. Photograph - Approximate Date: 1826-1827 A.D."+"\n"+"4. Thermometer - Approximate Date: 1718 A.D "+"\n"+"5. Telescope -Approximate Date: 1608 A.D."+"\n"+"6. Trophy (still in use) - Approximate Date: 1599 A.D."+"\n"+"7. Globe -Approximate Date: 1491 A.D."+"\n"+"8. Glasses - Approximate Date: 1436-1490 A.D."+"\n"+"9. Clock - Approximate Date: 1386 A.D."+"\n"+"10. Bar - Approximate Date: 900 A.D.",
            "1. Jocelyn Wildenstein"+"\n"+"2. Justin Jedlica"+ "\n"+"3. Rodrigo Alves "+"\n"+"4. Pixee Fox"+"\n"+"5. Natasha Crown"+"\n"+"6. Neven Ciganovic"+"\n"+"7. Bryan Ray"+"\n"+"8. Vinny Ohh"+"\n"+"9. Lacey Wildd's"+"\n"+"10. Herbert Chavez",
            "1. Hydrogen Powered Cars"+"\n"+"2. Automation"+ "\n"+"3. Antigravity"+"\n"+"4. Human Cloning"+"\n"+"5. Nanotechnology"+"\n"+"6. Artificial Intelligence"+"\n"+"7. Free Energy"+"\n"+"8. Hypersonic Transportation"+"\n"+"9. Genetic Engineering"+"\n"+"10. Robotics",
            "1. Thomas Edison "+"\n"+"2. The Wright Brothers "+ "\n"+"3. Benjamin Franklin "+"\n"+"4. Nikola Tesla"+"\n"+"5. Charles Babbage"+"\n"+"6. James Watt"+"\n"+"7. Alexander Bell "+"\n"+"8. Leonardo Da Vinci"+"\n"+"9. Galileo"+"\n"+"10. Tim Berners Lee ",
            "1. Freddie Mercury"+"\n"+"2. George Michael"+ "\n"+"3. Michael Jackson"+"\n"+"4. Nat King Cole"+"\n"+"5. Frank Sinatra"+"\n"+"6. Otis Redding"+"\n"+"7. Sam Cooke"+"\n"+"8. Al Green"+"\n"+"9. Marvin Gaye"+"\n"+"10. Luther Vandross",
            "1. Whitney Houston"+"\n"+"2. Aretha Franklin"+ "\n"+"3. Nina Simone"+"\n"+"4. Gladys Knight"+"\n"+"5. Etta James"+"\n"+"6. Janis Joplin"+"\n"+"7. Tina Turner"+"\n"+"8. Maria Callas"+"\n"+"9. Ella Fitzgerald"+"\n"+"10. Barbra Streisand",
            "1. Gordon James Ramsay"+"\n"+"2. Jamie Oliver"+ "\n"+"3. Wolfgang Puck"+"\n"+"4. Marco Pierre White"+"\n"+"5. Sanjeev Kapoor"+"\n"+"6. Thomas Keller"+"\n"+"7. Emeril Lagasse"+"\n"+"8. Charlie Trotter"+"\n"+"9. Paul Bocuse"+"\n"+"10. Anthony Bourdain",
            "1. Dr. Kianor Shah "+"\n"+"2. Dr. Gerald Niznick"+ "\n"+"3. Dr. Heidi Kohltfarber"+"\n"+"4. Dr. Howard Farran"+"\n"+"5. Dr. Gordon J. Christensen"+"\n"+"6. Dr. Dennis P. Tarnow"+"\n"+"7. Dr. Henriette Lerner"+"\n"+"8. Dr. George Freedman"+"\n"+"9. Dr. Jon Suzuki"+"\n"+"10. Dr. Thomas G. Wiedemann",
            "1. DKNY GOLDEN DELICIOUS MILLION DOLLAR FRAGRANCE BOTTLE"+"\n"+"2. CLIVE CHRISTIAN NO. 1 IMPERIAL MAJESTY PERFUME"+ "\n"+"3. BACCARAT LES LARMES SACREES DE THEBES"+"\n"+"4. CHANEL GRAND EXTRAIT"+"\n"+"5. CLIVE CHRISTIAN NO.1"+"\n"+"6. HERMÈS 24 FAUBOURG"+"\n"+"7. CARON POIVRE"+"\n"+"8. JOY BY JEAN PATOU"+"\n"+"9. JAR BOLT OF LIGHTNING"+"\n"+"10. ANNICK GOUTAL EAU D'HADRIEN",
            "1. IKEA"+"\n"+"2. Ashley HomeStore"+ "\n"+"3. Restoration Hardware"+"\n"+"4. Kartell"+"\n"+"5. Williams-Sonoma"+"\n"+"6. La-Z-Boy Furniture Galleries"+"\n"+"7. Raymour & Flanigan"+"\n"+"8. American Signature"+"\n"+"9. Roche Bobois"+"\n"+"10. Ethan Allen",
            "1. Silicone Cooking Utensils set"+"\n"+"2. StarPack Basics Silicone Kitchen Utensil Set"+ "\n"+"3. Miusco Non-Stick Silicone Cooking Utensils Set"+"\n"+"4. MIBOTE 14PCS Silicone Cooking Kitchen Utensils Set"+"\n"+"5. KitchenAid 17-Piece Tools and Gadget Set"+"\n"+"6. Farberware 5080445 Classic 17-Piece Tool and Gadget Set"+"\n"+"7. AILUKI Silicone Cooking Utensil Set"+"\n"+"8. HOME HERO Stainless Steel Kitchen Utensil Set"+"\n"+"9. IKEA 900.430.76 Fornufts 20 Pieces Flatware Set"+"\n"+"10. Stainless Steel Kitchens Utensils Set",
            "1. Nike"+"\n"+"2. Air Jordan"+ "\n"+"3. Adidas"+"\n"+"4. Reebok"+"\n"+"5. VANS"+"\n"+"6. CONVERSE"+"\n"+"7. NEW BALANCE"+"\n"+"8. UNDER ARMOUR"+"\n"+"9. DC SHOES"+"\n"+"10. PUMA",
            "1. Nike"+"\n"+"2. Adidas"+ "\n"+"3. Gucci"+"\n"+"4. Levis"+"\n"+"5. Polo Ralph Lauren"+"\n"+"6. Versace"+"\n"+"7. Calvin Klein"+"\n"+"8. American Eagle"+"\n"+"9. Aeropostale"+"\n"+"10. Abercrombie & Fitch",
            "1. Patek Philippe"+"\n"+"2. Vacheron Constantin"+ "\n"+"3. Audemars Piguet"+"\n"+"4. Blancpain"+"\n"+"5. Ulysse Nardin"+"\n"+"6. Jaeger-LeCoultre"+"\n"+"7. Omega"+"\n"+"8. Glashutte Original"+"\n"+"9. Rolex"+"\n"+"10. Jaquet Droz",
            "1. Apple"+"\n"+"2. Hewlett-Packard (HP)"+ "\n"+"3. Dell"+"\n"+"4. Lenovo"+"\n"+"5. Asus"+"\n"+"6. Acer"+"\n"+"7. Toshiba"+"\n"+"8. Samsung"+"\n"+"9. LG"+"\n"+"10. Sony",
            "1. Samsung"+"\n"+"2. LG"+ "\n"+"3. Sony"+"\n"+"4. Vizio"+"\n"+"5. TCL"+"\n"+"6. Hisense"+"\n"+"7. Panasonic"+"\n"+"8. Toshiba"+"\n"+"9. RCA"+"\n"+"10. Magnavox",
            "1. Ace & Tate"+"\n"+"2. Ray-Ban"+ "\n"+"3. Cubitts"+"\n"+"4. Kirk Originals"+"\n"+"5. Persol"+"\n"+"6. Finlay & Co"+"\n"+"7. Oliver Peoples"+"\n"+"8. Tom Ford"+"\n"+"9. Oakley"+"\n"+"10. Oliver Goldsmith",
            "1. Lego"+"\n"+"2. Mattel"+ "\n"+"3. Baby Einstein"+"\n"+"4. Nintendo"+"\n"+"5. Playmobil"+"\n"+"6. Hasbro"+"\n"+"7. LeapFrog"+"\n"+"8. Little Tikes"+"\n"+"9. K’NEX"+"\n"+"10. Radio Flyer",
            "1. Oral-B Pro-Health All-In-One Soft Bristle Toothbrush"+"\n"+"2. Curaprox CS 5460 Ultra Soft Toothbrush"+ "\n"+"3. Boie USA"+"\n"+"4. Colgate® 360° Enamel Health™ Soft Toothbrush for Sensitive Teeth"+"\n"+"5. Dr. Collins Ultra Soft & Super Slim Perio Toothbrush"+"\n"+"6. Oral-B Pro 1000 Electric Rechargeable Toothbrush"+"\n"+"7. Phillips Sonicare 2 Series"+"\n"+"8. GOBY"+"\n"+"9. FOREO ISSA 2"+"\n"+"10. Phillips Sonicare DiamondClean",
            "1. Adidas"+"\n"+"2. Reebok"+ "\n"+"3. Nike"+"\n"+"4. Puma"+"\n"+"5. Under Armour"+"\n"+"6. ESPN"+"\n"+"7. Gatorade"+"\n"+"8. EA Sports"+"\n"+"9. ASICS"+"\n"+"10. Skechers",
            "1. Medtronic plc"+"\n"+"2. Johnson & Johnson"+ "\n"+"3. Philips Healthcare"+"\n"+"4. GE Healthcare"+"\n"+"5. Siemens Healthineers"+"\n"+"6. Fresenius Medical Care"+"\n"+"7. Abbott Laboratories"+"\n"+"8. Becton Dickinson"+"\n"+"9. Cardinal Health"+"\n"+"10. Stryker",
            "1. Barefoot"+"\n"+"2. Concha Toro"+ "\n"+"3. Gallo"+"\n"+"4. Changyu"+"\n"+"5. Yellow Tail"+"\n"+"6. Sutter Home"+"\n"+"7. Robert Mondavi"+"\n"+"8. Hardys"+"\n"+"9. Beringer"+"\n"+"10. Great Wall",
            "1. Smith & Wesson"+"\n"+"2.  Remington Outdoor"+ "\n"+"3. Sturm, Ruger &Co."+"\n"+"4. SIG Sauer"+"\n"+"5. Heckler and Koch"+"\n"+"6. Mossberg"+"\n"+"7. Colt Defense"+"\n"+"8. Beretta"+"\n"+"9. Springfield Armory, Inc"+"\n"+"10. Savage Arms",
            "1. Starbucks"+"\n"+"2. Costa Coffee"+ "\n"+"3. Dunkin Donuts"+"\n"+"4. McCafe"+"\n"+"5. Tim Horton’s"+"\n"+"6. Gloria Jeans"+"\n"+"7. Nescafe"+"\n"+"8. Folgers"+"\n"+"9. Keurig"+"\n"+"10. Maxwell House",
            "1. Twinings"+"\n"+"2. Tazo"+ "\n"+"3. The Republic of Tea"+"\n"+"4. Lipton"+"\n"+"5. Yorkshire Tea"+"\n"+"6. Celestial Seasonings"+"\n"+"7. Harney & Sons"+"\n"+"8. Dilmah"+"\n"+"9. Bigelow"+"\n"+"10. Tetley",
            "1. Greyhound"+"\n"+"2. Saluki"+ "\n"+"3. Afghan Hound"+"\n"+"4. Vizsla"+"\n"+"5. Jack Russell terrier"+"\n"+"6. Dalmatian"+"\n"+"7. Borzoi"+"\n"+"8. Whippet"+"\n"+"9. Doberman Pinscher"+"\n"+"10. Border Collie",
            "1. Irish Thoroughbred"+"\n"+"2. Andalusian Horse"+ "\n"+"3. Hackney Horse"+"\n"+"4. Orlov Trotter"+"\n"+"5. Marwari Horse"+"\n"+"6. Gypsy horse\n"+"\n"+"7. Friesian Horse"+"\n"+"8. Morgan Horse"+"\n"+"9. Arabian Horse"+"\n"+"10. Carolina Marsh Tucky",
            "1. Canon EOS Rebel SL3 / 250D"+"\n"+"2. Olympus OM-D E-M10 III"+ "\n"+"3. Nikon D3500"+"\n"+"4. Panasonic TZ200/ZS200"+"\n"+"5. Canon Ixus 185 HS"+"\n"+"6. Nikon Coolpix W300"+"\n"+"7. Fujifilm X-T3"+"\n"+"8. Canon EOS 6D II"+"\n"+"9. Nikon Z 6"+"\n"+"10. Nikon D850",
            "1. T-Series: 139 million subscribers"+"\n"+"2. PewDiePie: 104 million subscribers"+ "\n"+"3. Cocomelon - Nursery Rhymes: 82 million subscribers"+"\n"+"4. SET India - 72 million subscribers"+"\n"+"5. 5-Minute Crafts: 66 million subscribers"+"\n"+"6. WWE: 60 million subscribers"+"\n"+"7. Canal KondZilla: 57 million subscribers"+"\n"+"8. Zee Music Company: 55 million subscribers"+"\n"+"9. Like Nastya: 54.8 million million subscribers"+"\n"+"10. Justin Bieber: 54.2 million subscribers",
            "1. Begin Your Day with Meditation"+"\n"+"2. Be Grateful for What You Have"+ "\n"+"3. Smile"+"\n"+"4. Start Your Day with a Healthy Breakfast"+"\n"+"5. Exercise Daily"+"\n"+"6. Manage Your Time as You Manage Your Finance"+"\n"+"7. Set Daily Goals with Intentions"+"\n"+"8. Seek Inspiration"+"\n"+"9. Save Steadily, Invest with All Prudence"+"\n"+"10. Budget and Track Your Spendings",
            "1. Facebook"+"\n"+"2. Twitter"+ "\n"+"3. Instagram"+"\n"+"4. Youtube"+"\n"+"5. Linkedin"+"\n"+"6. Baidu"+"\n"+"7. Google"+"\n"+"8. Plus.google.com (Google+)"+"\n"+"9. Pinterest"+"\n"+"10. Apple",
            "1. NIGER"+"\n"+"2. CENTRAL AFRICAN REPUBLIC"+ "\n"+"3. OUTH SUDAN"+"\n"+"4. CHAD"+"\n"+"5. BURUNDI"+"\n"+"6. SIERRA LEONE"+"\n"+"7. BURKINA FASO"+"\n"+"8. MALI"+"\n"+"9. LIBERIA"+"\n"+"10. MOZAMBIQUE",
            "1. Humans"+"\n"+"2. Mosquito"+ "\n"+"3. Tsetse Fly"+"\n"+"4. Saltwater Crocodile"+"\n"+"5. Black Mamba"+"\n"+"6. Pufferfish"+"\n"+"7. Box Jellyfish"+"\n"+"8. Golden Poison Dart Frog"+"\n"+"9. Cone Snail"+"\n"+"10. Cape Buffalo",
            "1. China"+"\n"+"2. Indonesia"+ "\n"+"3. Iran"+"\n"+"4. Turkey"+"\n"+"5. Japan"+"\n"+"6. Peru"+"\n"+"7. United States"+"\n"+"8. Italy"+"\n"+"9. \tAfghanistan"+"\n"+"10. India",
            "1. Golden Delicious apple "+"\n"+"2. Braeburn"+ "\n"+"3. Sekai Ichi"+"\n"+"4. Honeycrisp apple"+"\n"+"5. Fuji apple"+"\n"+"6. Lúcuma"+"\n"+"7. Cosmic Crisp (known to experts as WA 38)"+"\n"+"8. Armenian apricot"+"\n"+"9. Florida oranges"+"\n"+"10. Aydin inciri",
            "1. Iceland"+"\n"+"2. New Zealand"+ "\n"+"3. Portugal"+"\n"+"4. Austria"+"\n"+"5. Denmark"+"\n"+"6. Canada"+"\n"+"7. Singapore"+"\n"+"8. Slovenia"+"\n"+"9. Japan"+"\n"+"10. Czech Republic",
            "1. Mediterranean Sea"+"\n"+"2. Caribbean Sea"+ "\n"+"3. The South China Sea"+"\n"+"4. Bering Sea"+"\n"+"5. The Gulf of Mexico"+"\n"+"6. The Sea of Okhotsk"+"\n"+"7. The East China Sea"+"\n"+"8. Hudson Bay"+"\n"+"9. The Sea of Japan"+"\n"+"10. Andaman Sea",
            "1. Maldives"+"\n"+"2. Bora Bora"+ "\n"+"3. Palawan, Philippines"+"\n"+"4. Galapagos Islands, Ecuador"+"\n"+"5. Santorini, Greece"+"\n"+"6. Crete, Greece"+"\n"+"7. Seychelles"+"\n"+"8. Bali, Indonesia"+"\n"+"9. Fiji"+"\n"+"10. Moorea, French Polynesia",
            "1. J. Robert Oppenheimer — The atomic bomb"+"\n"+"2. Mikhail Kalashnikov — AK-47"+ "\n"+"3. Tim Berners Lee — the double slash"+"\n"+"4. Ethan Zuckerman — the pop-up advert"+"\n"+"5. Dong Nguyen — Flappy Bird"+"\n"+"6. Bob Propst — the office cubicle"+"\n"+"7. Vincent Connare — Comic Sans"+"\n"+"8. Tom Karen — Raleigh Chopper"+"\n"+"9. Kamran Loghman — Pepper spray"+"\n"+"10. John Sylvan — Coffee capsules",
            "1. A picnic lunch inspired Ernie Fraze to invent the pop top found on soda cans"+"\n"+"2. Joseph Friedman invents the bendable straw so his daughter can more easily drink a milkshake"+ "\n"+"3. Charlie Brannock creates the first accurate way to measure shoe size using toys"+"\n"+"4. James Goodfellow creates ATM pin numbers so people can take money out of the bank after hours"+"\n"+"5. Robert Kearns invents windshield wiper speeds and wins a $30 million lawsuit against auto companies that steal his idea"+"\n"+"6. Candy maker Sam Born invents a machine that inserts sticks into lollipops and receives a key to San Francisco"+"\n"+"7. Hymen Lipman creates the modern pencil by attaching an eraser at the end of it"+"\n"+"8. Twenty-somethings Scott Jones and Greg Carr bring voicemail to people everywhere"+"\n"+"9. Jack Clements designs a spill-free way to drink coffee on the go"+"\n"+"10. Margaret Knight fought a sexist employee to claim her rightful title as the inventor of the flat-bottomed paper bag",
            "1. Costa Rica"+"\n"+"2. Cyprus"+ "\n"+"3. Greece"+"\n"+"4. Malta"+"\n"+"5. Uganda"+"\n"+"6. Kenya"+"\n"+"7. Spain"+"\n"+"8. South Africa"+"\n"+"9. Mexico"+"\n"+"10. Portugal",
            "1. Afghanistan"+"\n"+"2. Ukraine"+ "\n"+"3. Iran"+"\n"+"4. USA"+"\n"+"5. Myanmar"+"\n"+"6. Macau"+"\n"+"7. Thailand"+"\n"+"8. Seychelles"+"\n"+"9. Russia"+"\n"+"10. Luxembourg",
            "1. Heliotrope (Heliotropium)"+"\n"+"2. Sweet Alyssum (Lobularia maritima)"+ "\n"+"3. Stock (Matthiola incana)"+"\n"+"4. Scented Geranium (Pelargonium graveolens)"+"\n"+"5. Lavender (Lavandula spp)"+"\n"+"6. Lily of the Valley (Convallaria majalis)"+"\n"+"7. Hyacinth (Hyacinthus) "+"\n"+"8. Gardenia (Gardenia jasminoides)"+"\n"+"9. Rose (Rosa spp) "+"\n"+"10. Lilac (Syringa spp) ",
            "1. Pufferfish"+"\n"+"2. Striated surgeonfish"+ "\n"+"3. Rough-skinned newt"+"\n"+"4. Comb stars"+"\n"+"5. Spanish fly"+"\n"+"6. Poison dart frog"+"\n"+"7. Cane toad"+"\n"+"8. Hawksbill sea turtles"+"\n"+"9. Hooded pitohui"+"\n"+"10. Asian tiger snake",
            "1. Use Indian Gensing"+"\n"+"2. Drink milk"+ "\n"+"3. Yoga exercises"+"\n"+"4. warm-up exercises"+"\n"+"5. Exercise"+"\n"+"6. Adequate and proper sleep"+"\n"+"7. Balanced diet"+"\n"+"8. Sunlight"+"\n"+"9. Get in good shape"+"\n"+"10. Drink water",
            "1. Python"+"\n"+"2. JavaScript"+ "\n"+"3. Java"+"\n"+"4. Swift"+"\n"+"5. GoLang"+"\n"+"6. C#"+"\n"+"7. C++"+"\n"+"8. Scala"+"\n"+"9. Kotlin"+"\n"+"10. Ruby",


    };
    String title[]={"Universities","Beautiful cities","Rich people","football players","Movies","Animation","Books","Actors","Actresses","Foods",
            "Genius people","Political countries","Hackers","It companies","Male models","Female models","Musics","Boxers","Successful women",
            "Applications","powerful Presidents","Places to see","Colours","Instagram Influencers","Fashion bloggers","Programming languages",
            "Mobile phones","Professors","Dirty cities","Dangerous diseases","Tv channels","Games","Towers","Tourist countries",
            "Cosmetics brand","Cars","Motorcycle","Painters","Expensive painting","Oldest Things","extreme plastic surgery","Invention of century",
            "Inventors","Male singers","Women singers","Chefs","Doctors","Perfume","Furniture companies","Kitchen utensils","Shoes Brands","Clothes Brands",
            "Watches","Computers","Television","Eye glasses","Toys","Toothbrush","Sport equipments","Medical devices","Wines","Guns","Coffee","Tea","Dog Breeds",
            "Horses","Camera","Youtube channels","Good Habits","Web sites","Poor countries","Dangerous animals","Countries with most earthquake",
            "Popular fruits","Safe countries","Big seas","Famous Island","Inventors who regret making them","Inventions whose inventors are unknown",
            "Countries with good weather","Countries producing drugs","Fragrant flowers","Poison Animals","High growth factors","Reasons for the short stature",
            "Countries with most imports","Countries with most exports","Countries had most victims of Corona","Countries producing electricity","Oil producing countries",
            "Active volcano","Countries with diamond mines","Countries with gold mines","Famous poet","Great religions of the world","The world most populous countries",
            "The world least populous countries","beautiful and famous hotels","Famous museums","Robots"};
    int photo[]={R.drawable.ic_university,R.drawable.beautifulcities,R.drawable.richperson,R.drawable.ic_footballplayers,R.drawable.ic_video_camera,R.drawable.ic_animation,R.drawable.ic_open_book,
            R.drawable.ic_celebrity,R.drawable.ic_actress,R.drawable.ic_food,R.drawable.ic_innovation,R.drawable.ic_political_countries,R.drawable.ic_hacker,R.drawable.itcompany,R.drawable.menmodel,R.drawable.modelwomen
            ,R.drawable.ic_music,R.drawable.ic_boxing,R.drawable.ic_success_women,R.drawable.ic_application,R.drawable.presidents,R.drawable.ic_place,R.drawable.ic_brush,R.drawable.ic_blogger,R.drawable.ic_fashion,R.drawable.ic_programming_lang
            ,R.drawable.ic_smartphone,R.drawable.ic_professor,R.drawable.dirtycities,R.drawable.ic_diseases_diagram,R.drawable.ic_tv,R.drawable.ic_game,R.drawable.ic_tokyo_tower,R.drawable.touristiccountries
            ,R.drawable.ic_cosmetics,R.drawable.ic_car,R.drawable.ic_motorcycle,R.drawable.ic_business_man,R.drawable.ic_painter,R.drawable.ic_mona_lisa,R.drawable.ic_antiquities,R.drawable.ic_surgery,R.drawable.ic_inventioncentury
            ,R.drawable.ic_inventor,R.drawable.ic_men_singer,R.drawable.ic_women_singer,R.drawable.ic_chef,R.drawable.ic_doctor,R.drawable.ic_perfume,R.drawable.ic_furniture,R.drawable.ic_kitchen,R.drawable.ic_shoes,R.drawable.ic_jacket
            ,R.drawable.ic_watch,R.drawable.ic_computer,R.drawable.ic_televesion,R.drawable.ic_glasses,R.drawable.ic_toys,R.drawable.ic_toothbrush,R.drawable.ic_soccer_ball,R.drawable.ic_healthcare_device,R.drawable.ic_wine,R.drawable.ic_gun,R.drawable.ic_coffee,R.drawable.ic_tea,R.drawable.ic_dog
            ,R.drawable.ic_horse,R.drawable.ic_camera,R.drawable.ic_youtube,R.drawable.ic_habit,R.drawable.ic_website,R.drawable.ic_poor,R.drawable.ic_snake,R.drawable.ic_earthquake
            ,R.drawable.ic_fruits,R.drawable.ic_safe_countries,R.drawable.ic_big_seas,R.drawable.ic_famous_island,R.drawable.regret,R.drawable.ic_unknown
            ,R.drawable.ic_good_weather,R.drawable.ic_drugs,R.drawable.ic_flowers,R.drawable.ic_poison_reptiles,R.drawable.ic_high_growth,R.drawable.short_growth
            ,R.drawable.ic_import,R.drawable.ic_export,R.drawable.corona,R.drawable.ic_electricity,R.drawable.ic_oil
            ,R.drawable.ic_volcano,R.drawable.ic_diamond,R.drawable.ic_gold,R.drawable.ic_poet,R.drawable.ic_religions,R.drawable.ic_most_populous
            ,R.drawable.least_populous,R.drawable.ic_hotel,R.drawable.ic_museums,R.drawable.ic_robot
    };


    String titles;
    int photos;
    int position;

    ImageView ivPhoto;
    TextView tvTitle,tvDetails;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.details);

        ivPhoto=findViewById(R.id.ivPhoto);
        tvTitle=findViewById(R.id.tvTitle);
        tvDetails=findViewById(R.id.tvDetails);

        photos=getIntent().getIntExtra("photos",0);
        titles=getIntent().getStringExtra("titles");
        //  detail=getIntent().getStringExtra("details");
        position=getIntent().getIntExtra("position",0);

        ivPhoto.setImageResource(photo[position]);
        tvTitle.setText(title[position]);
        tvDetails.setText(details[position]);

    }
}
